### ISSUE TITLE
remove constant columns from the design matrix

### ISSUE THREAD

**Issue by memming** [pillowlab/neuroGLM#1]
Those columns are useless for prediction, and completely collinear, redundant with bias term.

Make sure to keep the indices, so one can reconstruct the original form.

**Comment by jpillow** [comment]
Hi Memming,

Sorry, I'm not sure I understand the comment -- was this a "note to self"?

-J

**Comment by memming** [comment]
This is not a message to you. This is an issue tracker on github. I guess
you are subscribed to receive it as email.

On Fri, Jan 23, 2015 at 2:23 PM, Jonathan Pillow notifications@github.com
wrote:

> Hi Memming,
> 
> Sorry, I'm not sure I understand the comment -- was this a "note to self"?
> 
> -J
> 
> On Fri, Jan 23, 2015 at 2:19 PM, Il Memming Park <notifications@github.com
> 
> > wrote:
> > 
> > Those columns are useless for prediction, and completely co-linear,
> > redundant with bias term.
> > 
> > Make sure to keep the indices, so one can reconstruct the original form.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/pillowlab/neuroGLM/issues/1.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/pillowlab/neuroGLM/issues/1#issuecomment-71249472.

## 

Assistant Professor
Department of Neurobiology and Behavior
Stony Brook University
http://memming.wordpress.com | memming@Twitter
