### ISSUE TITLE
How to interpret filters

### ISSUE THREAD

**Issue by refactoriel** [pillowlab/neuroGLM#12]
When I run the tutorial.m file the two spike filters 'hist' and 'coupling' both approach 0 towards long lags. If you interpret the filters as a kind of gain that would mean that 243 ms after a spike the spike rate goes down to 0. Does that make sense or should those filters be shifted by 1?
I have the same issue if I run the code on my data.

If you look at Park et al. 2014 the filters all seem to approach 1 instead. That seems to make more sense to me.

**Comment by memming** [comment]
Park et al. 2014 are plotting 'gain' which are exponentiated filter values. Those gains are multiplied, while the raw filter/kernel values are ADDED before being exponentiated. Hence 0 means no influence in the raw filter, while 1 means no influence in the gain version.
