### ISSUE TITLE
Possibility to use this code for calcium imaging data

### ISSUE THREAD

**Issue by maristanye** [pillowlab/neuroGLM#17]
Hi,

I have been looking for models that allow to correlate neural activity to behavioral variables and found this repository. 

As I see this only refers to spike train data, but do you think it is possible to use this code with calcium data? Would be previous spike deconvolution from the calcium imaging data necessary before using it? Thanks in advance and sorry for the very basic question.

Eduardo Maristany

**Comment by memming** [comment]
Hi Eduardo,

This code generates the design matrix that can be used for any likelihood. For spiking, we typically use the Poisson likelihood, but the design matrix can be used for any other regression.

For Ca fluorescence data, you could use the Gaussian likelihood (i.e. ordinary least squares regression). In fact, the example code does linear regression as initialization for Poisson regression. The history filters would be equivalent to ones in the autoregressive model. You may want to start with 0 or 1 bin for it.

Memming
